/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteIndexRouteImport } from './routes/$site/index'
import { Route as SiteBoardRouteImport } from './routes/$site/board'

const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/$site/',
  path: '/$site/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBoardRoute = SiteBoardRouteImport.update({
  id: '/$site/board',
  path: '/$site/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sites': typeof SitesRoute
  '/$site/board': typeof SiteBoardRoute
  '/$site/': typeof SiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sites': typeof SitesRoute
  '/$site/board': typeof SiteBoardRoute
  '/$site': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sites': typeof SitesRoute
  '/$site/board': typeof SiteBoardRoute
  '/$site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sites' | '/$site/board' | '/$site/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sites' | '/$site/board' | '/$site'
  id: '__root__' | '/' | '/sites' | '/$site/board' | '/$site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitesRoute: typeof SitesRoute
  SiteBoardRoute: typeof SiteBoardRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$site/': {
      id: '/$site/'
      path: '/$site'
      fullPath: '/$site/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$site/board': {
      id: '/$site/board'
      path: '/$site/board'
      fullPath: '/$site/board'
      preLoaderRoute: typeof SiteBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitesRoute: SitesRoute,
  SiteBoardRoute: SiteBoardRoute,
  SiteIndexRoute: SiteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
